2024-05-09 17:24:43,741 - app - ERROR - An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback:
Traceback (most recent call last):
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\werkzeug\routing\map.py", line 631, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-05-09 17:59:44,149 - app - ERROR - An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback:
Traceback (most recent call last):
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\werkzeug\routing\map.py", line 631, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-05-09 17:59:45,093 - app - ERROR - An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback:
Traceback (most recent call last):
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\ruzae\PycharmProjects\Algin\venv\lib\site-packages\werkzeug\routing\map.py", line 631, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

